### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gia534**
Adding my name to the end of the README.md file on February 4, 2021, at 11:18 pm.

### CODE REVIEW

**Comment by scharffc** [comment]
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b gia534-patch-1 master
git pull https://github.com/gia534/courses.git patch-1

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff gia534-patch-1
git push origin master

**Comment by gia534** [comment]
I followed the steps, I want to make sure that it went through and the issue has been resolved.

**Comment by scharffc** [comment]
@gia534 

I cannot merge. There is no new pull request.

**Comment by scharffc** [comment]
I did not get a new pull request

**Comment by gia534** [comment]
When I was trying to edit this last night I pressed the delete button instead of the edit button and I thought I had lost this pull request entirely cause I couldn't find it. So I created a new one. Are you able to see the new one?

**Comment by scharffc** [comment]
You can see if there is a pull request. And there is none for now.

[image: image.png]

**Pull request closed without merging**
