### PR TITLE
added my name and date to readme

### PR DESCRIPTION
**Pull request by aaabdoulaye**

### CODE REVIEW

**Comment by scharffc** [comment]
@aaabdoulaye

Great work!

Please be sure to put your infos here: http://bit.ly/23YVpiA 

Avez vous deja utilise git et github dans le passe ou c'etait la permiere fois?

**Comment by aaabdoulaye** [comment]
thanks,
oui j'ai déja utilise git avec bitbucket.
github c'est ma première vrai expérience.

2016-02-12 20:18 GMT+00:00 Christelle Scharff <notifications@github.com>:

> @aaabdoulaye <https://github.com/aaabdoulaye>
>
> Great work!
>
> Please be sure to put your infos here: http://bit.ly/23YVpiA
>
> Avez vous deja utilise git et github dans le passe ou c'etait la permiere
> fois?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paceuniversity/courses/pull/96#issuecomment-183473676>
> .
>



-- 
Cordialement Abdoul Aziz ABDOULAYE, CAPM

**Comment by scharffc** [comment]
Great. Please finalize the tutorial to use the issues and the wiki.

**Comment by aaabdoulaye** [comment]
already done.

2016-02-12 21:29 GMT+00:00 Christelle Scharff <notifications@github.com>:

> Great. Please finalize the tutorial to use the issues and the wiki.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paceuniversity/courses/pull/96#issuecomment-183494729>
> .
>



-- 
Cordialement Abdoul Aziz ABDOULAYE, CAPM

**Comment by scharffc** [comment]
One comment. As you answer to the notifications by email instead of through
the interface (
https://github.com/paceuniversity/courses/pull/96#issuecomment-183497101)
it is a good practice to remove the email before answering.



​

**Comment by aaabdoulaye** [comment]
I was answering by email. I have remove it. thanx for your suggestion

**Pull request merged**
