### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by younggg96**

### CODE REVIEW

**Comment by scharffc** [comment]
There are conflicts. Read here https://github.com/paceuniversity/courses/pull/444 how to resolve conflicts. @younggg96

**Comment by younggg96** [comment]
Hi professor, I don't know how to fix this conflict.

**Comment by scharffc** [comment]
@younggg96 

If you click on the Resolve conflict button, it will show you the list of commands you need to use.

image

**Comment by younggg96** [comment]
Now there is no conflict, but I cannot see my name in the readme.md. I have no idea how to deal with that.

**Pull request merged**
